const TECHNICAL_KEYWORDS = [
  'software', 'developer', 'engineer', 'engineering', 'programming', 'code', 'coding',
  'frontend', 'backend', 'fullstack', 'full-stack', 'full stack', 'web', 'api', 'rest',
  'graphql', 'react', 'angular', 'vue', 'node', 'javascript', 'typescript', 'java',
  'python', 'golang', 'go ', 'c++', 'c#', '.net', 'php', 'ruby', 'rust', 'kotlin',
  'swift', 'sql', 'database', 'mysql', 'postgres', 'mongodb', 'oracle', 'nosql',
  'cloud', 'aws', 'azure', 'gcp', 'devops', 'docker', 'kubernetes', 'k8s', 'ci/cd',
  'terraform', 'linux', 'unix', 'sysadmin', 'sre', 'infrastructure',
  'machine learning', 'ai', 'artificial intelligence', 'data science', 'data engineer',
  'data analyst', 'big data', 'analytics', 'nlp', 'computer vision', 'deep learning',
  'data scientist', 'llm', 'data',
  'security', 'cybersecurity', 'cyber', 'penetration', 'pentest', 'ethical hacking',
  'network', 'soc', 'incident response', 'vulnerability',
  'mobile', 'ios', 'android', 'react native', 'flutter', 'dart',
  'ui/ux', 'ui designer', 'ux designer', 'product designer', 'figma', 'designer',
  'qa', 'quality assurance', 'test', 'testing', 'sdet', 'automation',
  'backend', 'full stack', 'architect', 'technical', 'tech lead', 'scrum', 'agile',
  'it ', 'information technology', 'helpdesk', 'support engineer', 'devops engineer',
  'blockchain', 'web3', 'game developer', 'embedded', 'iot', 'robotics', 'gis',
  'sap', 'salesforce', 'erp', 'crm developer', 'bi developer', 'etl',
  'product manager technical', 'staff engineer', 'principal engineer',
];

const NON_TECHNICAL_KEYWORDS = [
  'hr', 'human resource', 'recruiter', 'recruitment', 'talent', 'people', 'payroll',
  'sales', 'account executive', 'sales rep', 'business development', 'bd ', 'account manager',
  'inside sales', 'field sales', 'revenue',
  'marketing', 'seo', 'content', 'copywriter', 'social media', 'digital marketing',
  'brand', 'branding', 'growth', 'performance marketing', 'advertising', 'pr ', 'public relations',
  'finance', 'accountant', 'accounting', 'financial', 'audit', 'auditor', 'tax', 'bookkeeper',
  'banking', 'bank', 'loan', 'credit', 'investment', 'wealth', 'teller', 'insurance',
  'legal', 'lawyer', 'attorney', 'paralegal', 'compliance', 'counsel',
  'healthcare', 'nurse', 'nursing', 'doctor', 'physician', 'medical', 'pharmacy', 'pharmacist',
  'clinical', 'caregiver', 'dentist', 'therapist',
  'operations', 'operation', 'logistics', 'supply chain', 'procurement', 'warehouse',
  'customer support', 'customer service', 'support specialist', 'call center', 'helpdesk',
  'client service', 'care', 'concierge',
  'education', 'teacher', 'teaching', 'instructor', 'tutor', 'professor', 'trainer',
  'admin', 'administrative', 'executive assistant', 'receptionist', 'office',
  'real estate', 'property', 'agent',
  'hospitality', 'restaurant', 'food', 'barista', 'chef', 'waiter', 'hotel',
  'retail', 'store', 'cashier', 'merchandiser',
  'sales executive', 'customer success', 'relationship manager', 'consultant',
];

const TECHNICAL_CATEGORIES = {
  'Software Development': ['software', 'developer', 'programmer', 'frontend', 'backend', 'full stack', 'web developer', 'application developer', 'engineer'],
  'AI': ['artificial intelligence', 'ai ', 'llm', 'machine learning engineer', 'ai engineer', 'nlp'],
  'Machine Learning': ['machine learning', 'ml ', 'deep learning', 'computer vision', 'data scientist'],
  'Data Science': ['data science', 'data analyst', 'data engineer', 'analytics', 'big data', 'bi developer', 'etl'],
  'DevOps': ['devops', 'site reliability', 'sre', 'ci/cd', 'infrastructure', 'release engineer'],
  'Cloud': ['cloud', 'aws', 'azure', 'gcp', 'terraform', 'cloud architect'],
  'Cyber Security': ['security', 'cybersecurity', 'cyber', 'penetration', 'ethical', 'soc', 'incident response', 'vulnerability'],
  'Mobile Development': ['mobile', 'ios', 'android', 'react native', 'flutter'],
  'UI/UX': ['ui/ux', 'ui designer', 'ux designer', 'product designer', 'figma', 'user experience', 'user interface'],
  'QA': ['qa', 'quality assurance', 'test engineer', 'sdet', 'automation engineer', 'tester'],
  'IT & Support': ['it ', 'helpdesk', 'support engineer', 'technical support', 'sysadmin', 'network'],
  'Other Technical': ['architect', 'tech lead', 'scrum master', 'blockchain', 'game developer', 'embedded', 'sap', 'salesforce', 'crm developer'],
};

const NON_TECHNICAL_CATEGORIES = {
  'HR': ['hr', 'human resource', 'recruiter', 'recruitment', 'talent', 'people ops', 'payroll', 'sourcer'],
  'Sales': ['sales', 'account executive', 'business development', 'account manager', 'inside sales', 'field sales', 'sales rep', 'sales executive'],
  'Marketing': ['marketing', 'seo', 'content', 'copywriter', 'social media', 'digital marketing', 'brand', 'growth', 'performance marketing', 'advertising', 'public relations', 'pr '],
  'Finance': ['finance', 'accountant', 'accounting', 'financial', 'audit', 'tax', 'bookkeeper', 'controller'],
  'Banking': ['banking', 'bank ', 'loan', 'credit', 'investment', 'wealth', 'teller', 'insurance', 'mortgage'],
  'Legal': ['legal', 'lawyer', 'attorney', 'paralegal', 'compliance', 'counsel'],
  'Healthcare': ['healthcare', 'nurse', 'nursing', 'doctor', 'physician', 'medical', 'pharmacy', 'pharmacist', 'clinical', 'caregiver', 'dentist', 'therapist', 'care'],
  'Operations': ['operations', 'logistics', 'supply chain', 'procurement', 'warehouse', 'operations manager'],
  'Customer Support': ['customer support', 'customer service', 'call center', 'client service', 'support specialist', 'concierge'],
  'Education': ['education', 'teacher', 'teaching', 'instructor', 'tutor', 'professor', 'trainer', 'curriculum'],
  'Administration': ['admin', 'administrative', 'executive assistant', 'receptionist', 'office manager'],
  'Business & Consulting': ['business', 'consultant', 'analyst business', 'project manager', 'product manager', 'accounting'],
  'Retail & Hospitality': ['retail', 'hospitality', 'restaurant', 'hotel', 'store', 'cashier', 'chef', 'barista', 'waiter'],
  'Other Non-Technical': ['real estate', 'property', 'agent', 'customer success', 'relationship manager'],
};

const ALL_SKILLS = [
  'javascript', 'typescript', 'python', 'java', 'c++', 'c#', 'go', 'golang', 'rust', 'ruby',
  'php', 'swift', 'kotlin', 'dart', 'scala', 'perl', 'shell', 'bash',
  'react', 'react native', 'angular', 'vue', 'svelte', 'next.js', 'node.js', 'node',
  'express', 'django', 'flask', 'spring', 'spring boot', 'laravel', 'rails', 'asp.net',
  'graphql', 'rest', 'api', 'microservices',
  'html', 'css', 'sass', 'tailwind', 'bootstrap',
  'sql', 'mysql', 'postgresql', 'postgres', 'mongodb', 'redis', 'elasticsearch', 'cassandra',
  'oracle', 'sqlite', 'dynamodb', 'nosql',
  'aws', 'azure', 'gcp', 'google cloud', 'cloud', 'terraform', 'serverless',
  'docker', 'kubernetes', 'k8s', 'jenkins', 'ci/cd', 'git', 'github', 'gitlab', 'ansible',
  'linux', 'devops', 'sre', 'nginx',
  'machine learning', 'deep learning', 'tensorflow', 'pytorch', 'keras', 'nlp', 'computer vision',
  'data science', 'pandas', 'numpy', 'scikit-learn', 'spark', 'hadoop', 'airflow', 'etl',
  'tableau', 'power bi', 'excel',
  'security', 'cybersecurity', 'penetration testing', 'ethical hacking', 'network security',
  'compliance', 'iso 27001', 'soc 2',
  'salesforce', 'sap', 'erp', 'crm', 'hubspot',
  'figma', 'adobe xd', 'sketch', 'photoshop', 'illustrator', 'ui', 'ux', 'wireframing',
  'testing', 'qa', 'selenium', 'cypress', 'jest', 'junit',
  'agile', 'scrum', 'kanban', 'jira', 'product management',
  'communication', 'leadership', 'teamwork', 'problem solving', 'project management',
  'sales', 'negotiation', 'marketing', 'seo', 'content writing', 'copywriting', 'analytics',
  'hr', 'recruiting', 'payroll', 'customer service', 'support', 'accounting', 'bookkeeping',
  'finance', 'tax', 'legal', 'writing', 'presentation', 'time management',
];

const SKILL_EXTRACT = {
  'javascript': ['javascript', 'js', 'nodejs', 'node.js', 'typescript', 'react', 'vue', 'angular', 'react.js', 'next.js', 'vue.js', 'node', 'jquery', 'ecmascript'],
  'typescript': ['typescript', 'ts', 'tsx'],
  'python': ['python', 'django', 'flask', 'fastapi', 'pandas', 'numpy', 'scikit-learn', 'pytest', 'django rest'],
  'java': ['java', 'spring boot', 'spring', 'hibernate', 'j2ee', 'javafx', 'core java', 'jdk'],
  'react': ['react', 'reactjs', 'react.js', 'react native', 'redux', 'next.js'],
  'node.js': ['node', 'node.js', 'nodejs', 'express', 'express.js', 'expressjs', 'nestjs', 'npm', 'backend'],
  'express': ['express', 'express.js', 'expressjs'],
  'mongodb': ['mongodb', 'mongo', 'mongoose', 'nosql'],
  'sql': ['sql', 'mysql', 'postgresql', 'postgres', 'sql server', 'oracle', 'pl/sql', 'tsql'],
  'aws': ['aws', 'amazon web services', 'ec2', 's3', 'lambda', 'cloudfront', 'route 53', 'iam'],
  'azure': ['azure', 'microsoft azure'],
  'docker': ['docker', 'dockerize', 'dockerized', 'containers', 'containerization'],
  'kubernetes': ['kubernetes', 'k8s', 'helm', 'eks', 'gke', 'aks'],
  'git': ['git', 'github', 'gitlab', 'bitbucket', 'version control'],
  'linux': ['linux', 'unix', 'ubuntu', 'debian', 'centos', 'red hat', 'bash', 'shell scripting'],
  'machine learning': ['machine learning', 'ml', 'deep learning', 'tensorflow', 'pytorch', 'keras', 'scikit', 'neural network', 'nlp', 'natural language processing', 'computer vision', 'llm', 'openai'],
  'data science': ['data science', 'data analysis', 'data analytics', 'pandas', 'numpy', 'scipy', 'spark', 'pyspark', 'hadoop', 'big data', 'etl', 'airflow', 'tableau', 'power bi', 'jupyter'],
  'qa': ['qa', 'quality assurance', 'testing', 'test engineer', 'selenium', 'cypress', 'jest', 'junit', 'pytest', 'manual testing', 'automation testing', 'sdet'],
  'c++': ['c++', 'cpp', 'c plus plus'],
  'c#': ['c#', 'csharp', 'c sharp', '.net', 'asp.net', 'dotnet'],
  'go': ['go', 'golang', 'go lang'],
  'ruby': ['ruby', 'ruby on rails', 'rails', 'sinatra'],
  'php': ['php', 'laravel', 'wordpress', 'symfony', 'codeigniter'],
  'swift': ['swift', 'ios', 'xcode'],
  'kotlin': ['kotlin', 'android studio', 'android'],
  'flutter': ['flutter', 'dart'],
  'react native': ['react native'],
  'ui/ux': ['ui', 'ux', 'ui/ux', 'figma', 'sketch', 'adobe xd', 'prototyping', 'wireframe', 'user interface', 'user experience', 'design'],
  'devops': ['devops', 'ci/cd', 'jenkins', 'github actions', 'gitlab ci', 'ansible', 'terraform', 'puppet', 'chef', 'sre', 'site reliability'],
  'cybersecurity': ['cybersecurity', 'cyber security', 'security', 'penetration', 'ethical hacking', 'soc', 'infosec', 'information security', 'vulnerability assessment', 'nist', 'iso 27001'],
  'salesforce': ['salesforce', 'sfdc', 'apex', 'lightning', 'sales cloud'],
  'sap': ['sap', 'sap fico', 'sap abap', 'sap sd'],
  'agile': ['agile', 'scrum', 'kanban', 'sprint', 'jira', 'confluence'],
  'communication': ['communication', 'verbal', 'written communication', 'interpersonal', 'presentation'],
  'leadership': ['leadership', 'team lead', 'mentor', 'management', 'people management', 'coaching'],
  'project management': ['project management', 'pmp', 'project manager', 'program management', 'stakeholder'],
  'sales': ['sales', 'b2b sales', 'b2c sales', 'cold calling', 'lead generation', 'negotiation', 'closing', 'salesforce', 'crm', 'outbound', 'inside sales'],
  'marketing': ['marketing', 'digital marketing', 'seo', 'sem', 'content marketing', 'email marketing', 'social media', 'google ads', 'facebook ads', 'growth marketing', 'brand', 'copywriting', 'conversion'],
  'hr': ['hr', 'human resources', 'recruiting', 'recruitment', 'talent acquisition', 'onboarding', 'payroll', 'employee relations', 'sourcing'],
  'customer service': ['customer service', 'customer support', 'client service', 'support', 'call center', 'helpdesk', 'crm', 'ticketing', 'zendesk'],
  'accounting': ['accounting', 'bookkeeping', 'quickbooks', 'xero', 'accounts payable', 'accounts receivable', 'reconciliation', 'financial reporting'],
  'finance': ['finance', 'financial analysis', 'investment', 'risk management', 'budgeting', 'forecasting', 'valuation'],
  'legal': ['legal', 'law', 'compliance', 'contracts', 'regulatory', 'paralegal', 'due diligence'],
};

const SKILL_ALIASES = {
  js: 'javascript',
  javascript: 'javascript',
  node: 'node.js',
  nodejs: 'node.js',
  'node.js': 'node.js',
  reactjs: 'react',
  'react.js': 'react',
  golang: 'go',
  postgres: 'postgresql',
  cpp: 'c++',
  k8s: 'kubernetes',
  'machine learning': 'machine learning',
  ml: 'machine learning',
  'data analysis': 'data science',
  'data analytics': 'data science',
  'data science': 'data science',
  'artificial intelligence': 'ai',
  ai: 'ai',
  ui: 'ui/ux',
  ux: 'ui/ux',
  'ui/ux': 'ui/ux',
  design: 'ui/ux',
  'frontend': 'frontend',
  'backend': 'backend',
  'full stack': 'fullstack',
  fullstack: 'fullstack',
  'quality assurance': 'qa',
  testing: 'qa',
  test: 'qa',
  'information security': 'cybersecurity',
  'cyber security': 'cybersecurity',
  cybersecurity: 'cybersecurity',
  'cloud computing': 'cloud',
  cloud: 'cloud',
  'communication skills': 'communication',
  'customer success': 'customer success',
  'business development': 'business development',
  'project management': 'project management',
  'digital marketing': 'marketing',
  marketing: 'marketing',
  'customer service': 'customer service',
  'customer support': 'customer service',
  support: 'customer service',
  sales: 'sales',
  'account management': 'sales',
  'human resources': 'hr',
  recruiting: 'hr',
  recruitment: 'hr',
  finance: 'finance',
  accounting: 'accounting',
  legal: 'legal',
  compliance: 'legal',
};

module.exports = {
  TECHNICAL_KEYWORDS,
  NON_TECHNICAL_KEYWORDS,
  TECHNICAL_CATEGORIES,
  NON_TECHNICAL_CATEGORIES,
  ALL_SKILLS,
  SKILL_EXTRACT,
  SKILL_ALIASES,
};
