const TECHNICAL_KEYWORDS = [
  'software', 'developer', 'engineer', 'engineering', 'programming', 'code', 'coding',
  'frontend', 'backend', 'fullstack', 'full-stack', 'full stack', 'web development', 'web developer',
  'api', 'rest api', 'graphql', 'microservices',
  'react', 'angular', 'vue', 'node', 'nodejs', 'javascript', 'typescript', 'java',
  'python', 'golang', 'go developer', 'c++', 'c#', '.net', 'dotnet', 'php', 'ruby', 'rust', 'kotlin',
  'swift', 'sql', 'database', 'mysql', 'postgres', 'postgresql', 'mongodb', 'oracle', 'nosql', 'redis',
  'cloud', 'aws', 'azure', 'gcp', 'devops', 'docker', 'kubernetes', 'k8s', 'ci/cd',
  'terraform', 'linux', 'unix', 'sysadmin', 'sre', 'infrastructure',
  'machine learning', 'artificial intelligence', 'data science', 'data engineer',
  'data analyst', 'big data', 'nlp', 'computer vision', 'deep learning',
  'data scientist', 'llm', 'generative ai', 'ai engineer', 'ml engineer',
  'cybersecurity', 'security engineer', 'penetration testing', 'ethical hacking',
  'network engineer', 'soc analyst', 'vulnerability',
  'mobile developer', 'ios developer', 'android developer', 'react native', 'flutter',
  'ui/ux', 'ui designer', 'ux designer', 'product designer', 'figma',
  'qa engineer', 'quality assurance', 'test engineer', 'sdet', 'automation testing',
  'tech lead', 'solutions architect', 'software architect',
  'information technology', 'helpdesk technician', 'systems administrator',
  'blockchain', 'web3', 'solidity', 'smart contract', 'embedded systems', 'iot', 'robotics',
  'salesforce developer', 'sap developer', 'crm developer', 'bi developer', 'etl developer',
];

const NON_TECHNICAL_KEYWORDS = [
  'marketing', 'marketer', 'digital marketing', 'growth marketing', 'social media', 'social media manager',
  'brand manager', 'campaign manager', 'seo specialist', 'sem specialist', 'content marketing', 'email marketing',
  'performance marketing', 'product marketing', 'affiliate marketing', 'public relations', 'pr manager', 'advertising',
  'translator', 'translation', 'interpreter', 'localization', 'localization specialist', 'linguist', 'language specialist', 'transcriptionist',
  'business executive', 'business development', 'business development executive', 'bde', 'bdr', 'sdr', 'account executive',
  'sales executive', 'sales representative', 'sales rep', 'sales manager', 'client executive', 'operations executive',
  'executive assistant', 'administrative assistant', 'office administrator', 'relationship manager', 'inside sales', 'field sales', 'corporate sales',
  'human resources', 'talent acquisition', 'recruiter', 'recruitment', 'people operations', 'payroll', 'sourcer',
  'content writer', 'copywriter', 'content creator', 'editor', 'journalist', 'technical writer',
  'accountant', 'accounting', 'financial analyst', 'auditor', 'tax specialist', 'bookkeeper', 'controller',
  'investment banking', 'credit analyst', 'wealth manager', 'underwriter', 'insurance agent', 'banker',
  'legal counsel', 'attorney', 'lawyer', 'paralegal', 'compliance officer',
  'registered nurse', 'physician', 'medical assistant', 'pharmacist', 'therapist', 'clinic',
  'operations manager', 'supply chain', 'logistics coordinator', 'procurement specialist', 'warehouse supervisor',
  'customer support', 'customer service representative', 'client success', 'customer success manager', 'call center', 'telecaller',
  'teacher', 'instructor', 'professor', 'academic tutor', 'corporate trainer',
  'receptionist', 'front desk', 'real estate agent', 'property manager',
  'hotel manager', 'restaurant manager', 'executive chef', 'store manager', 'retail associate', 'cashier',
];

const TECHNICAL_CATEGORIES = {
  'Software Development': ['software', 'developer', 'programmer', 'frontend', 'backend', 'full stack', 'web developer', 'application developer', 'engineer', 'react', 'node', 'java', 'python'],
  'AI & Data Science': ['artificial intelligence', 'ai', 'machine learning', 'ml', 'deep learning', 'data science', 'data engineer', 'data analyst', 'nlp', 'computer vision', 'llm'],
  'DevOps & Cloud': ['devops', 'cloud', 'aws', 'azure', 'gcp', 'docker', 'kubernetes', 'sre', 'ci/cd', 'terraform', 'infrastructure'],
  'Cyber Security': ['security', 'cybersecurity', 'penetration', 'ethical', 'soc', 'incident response', 'vulnerability', 'infosec'],
  'Mobile Development': ['mobile', 'ios', 'android', 'react native', 'flutter', 'swift', 'kotlin'],
  'UI/UX Design': ['ui/ux', 'ui designer', 'ux designer', 'product designer', 'figma', 'user experience', 'user interface'],
  'QA & Testing': ['qa', 'quality assurance', 'test engineer', 'sdet', 'automation engineer', 'tester', 'selenium', 'cypress'],
  'IT & Infrastructure': ['it', 'helpdesk', 'support engineer', 'technical support', 'sysadmin', 'network', 'system administrator'],
  'Other Technical': ['architect', 'tech lead', 'scrum master', 'blockchain', 'game developer', 'embedded', 'sap', 'salesforce'],
};

const NON_TECHNICAL_CATEGORIES = {
  'HR & Talent': ['human resources', 'recruiter', 'recruitment', 'talent acquisition', 'people ops', 'payroll', 'sourcer'],
  'Sales & BD': ['sales', 'account executive', 'business development', 'account manager', 'inside sales', 'field sales', 'sales rep'],
  'Marketing & Content': ['marketing', 'seo', 'content writer', 'copywriter', 'social media', 'digital marketing', 'brand', 'growth', 'advertising'],
  'Finance & Accounting': ['finance', 'accountant', 'accounting', 'financial analyst', 'audit', 'tax', 'bookkeeper', 'controller'],
  'Banking & Insurance': ['banking', 'bank', 'loan', 'credit', 'investment', 'wealth', 'insurance', 'mortgage'],
  'Legal & Compliance': ['legal', 'lawyer', 'attorney', 'paralegal', 'compliance', 'counsel'],
  'Healthcare & Medical': ['healthcare', 'nurse', 'doctor', 'physician', 'medical', 'pharmacy', 'pharmacist', 'clinical', 'therapist'],
  'Operations & Supply Chain': ['operations', 'logistics', 'supply chain', 'procurement', 'warehouse', 'operations manager'],
  'Customer Support': ['customer support', 'customer service', 'call center', 'client service', 'support specialist', 'customer success'],
  'Education & Training': ['education', 'teacher', 'instructor', 'tutor', 'professor', 'trainer'],
  'Administration': ['admin', 'administrative', 'executive assistant', 'receptionist', 'office manager'],
  'Other Non-Technical': ['real estate', 'hospitality', 'retail', 'restaurant', 'store manager'],
};

const ALL_SKILLS = [
  'javascript', 'typescript', 'python', 'java', 'c++', 'c#', 'go', 'rust', 'ruby',
  'php', 'swift', 'kotlin', 'dart', 'scala', 'bash', 'shell',
  'react', 'react native', 'angular', 'vue', 'svelte', 'next.js', 'node.js', 'express',
  'django', 'flask', 'fastapi', 'spring', 'spring boot', 'laravel', 'rails', 'asp.net',
  'graphql', 'rest api', 'microservices',
  'html', 'css', 'sass', 'tailwind', 'bootstrap',
  'sql', 'mysql', 'postgresql', 'mongodb', 'redis', 'elasticsearch', 'cassandra', 'oracle', 'nosql',
  'aws', 'azure', 'gcp', 'terraform', 'docker', 'kubernetes', 'jenkins', 'ci/cd', 'git', 'github',
  'linux', 'devops', 'sre', 'nginx',
  'machine learning', 'deep learning', 'tensorflow', 'pytorch', 'nlp', 'computer vision', 'llm',
  'data science', 'pandas', 'numpy', 'scikit-learn', 'spark', 'etl', 'tableau', 'power bi',
  'cybersecurity', 'penetration testing', 'network security',
  'salesforce', 'sap',
  'figma', 'adobe xd', 'ui/ux',
  'testing', 'qa', 'selenium', 'cypress', 'jest', 'junit',
  'agile', 'scrum', 'jira',
  'sales', 'marketing', 'seo', 'content writing', 'hr', 'recruiting', 'accounting', 'finance',
];

const SKILL_EXTRACT = {
  'java': ['java', 'core java', 'spring boot', 'spring framework', 'spring mvc', 'hibernate', 'j2ee', 'jvm', 'jdk', 'maven', 'gradle'],
  'python': ['python', 'django', 'flask', 'fastapi', 'pandas', 'numpy', 'scikit-learn', 'pytest', 'celery', 'pyspark'],
  'javascript': ['javascript', 'js', 'es6', 'vanilla js', 'ecmascript', 'jquery'],
  'typescript': ['typescript', 'ts', 'tsx'],
  'react': ['react', 'reactjs', 'react.js', 'redux', 'redux toolkit'],
  'next.js': ['next.js', 'nextjs'],
  'angular': ['angular', 'angularjs', 'angular.js'],
  'vue': ['vue', 'vuejs', 'vue.js', 'vuex', 'pinia'],
  'node.js': ['node', 'node.js', 'nodejs'],
  'express': ['express', 'express.js', 'expressjs'],
  'fastapi': ['fastapi', 'fast api'],
  'django': ['django', 'django rest'],
  'spring boot': ['spring boot', 'spring-boot', 'spring framework'],
  'c++': ['c++', 'cpp'],
  'c#': ['c#', 'csharp', 'c sharp', '.net', 'asp.net', 'dotnet'],
  'go': ['go', 'golang'],
  'rust': ['rust', 'rustlang'],
  'ruby': ['ruby', 'ruby on rails', 'rails'],
  'php': ['php', 'laravel', 'symfony', 'codeigniter'],
  'swift': ['swift', 'ios', 'xcode', 'swiftui'],
  'kotlin': ['kotlin', 'android', 'android studio'],
  'flutter': ['flutter', 'dart'],
  'react native': ['react native'],
  'sql': ['sql', 'mysql', 'postgresql', 'postgres', 'oracle', 'sql server', 'sqlite', 'pl/sql', 't-sql'],
  'mongodb': ['mongodb', 'mongo', 'mongoose', 'nosql'],
  'redis': ['redis', 'memcached'],
  'aws': ['aws', 'amazon web services', 'ec2', 's3', 'lambda', 'dynamodb', 'cloudformation'],
  'azure': ['azure', 'microsoft azure'],
  'gcp': ['gcp', 'google cloud', 'bigquery'],
  'docker': ['docker', 'containerization', 'docker-compose'],
  'kubernetes': ['kubernetes', 'k8s', 'helm'],
  'devops': ['devops', 'ci/cd', 'jenkins', 'github actions', 'gitlab ci', 'terraform', 'ansible', 'sre', 'site reliability'],
  'git': ['git', 'github', 'gitlab', 'bitbucket'],
  'linux': ['linux', 'unix', 'ubuntu', 'debian', 'bash', 'shell scripting'],
  'graphql': ['graphql', 'apollo'],
  'rest api': ['rest api', 'restful', 'microservices', 'api development'],
  'machine learning': ['machine learning', 'ml', 'deep learning', 'tensorflow', 'pytorch', 'keras', 'scikit-learn', 'nlp', 'computer vision', 'llm', 'generative ai', 'openai', 'transformers'],
  'data science': ['data science', 'data analysis', 'data analytics', 'spark', 'hadoop', 'etl', 'airflow', 'tableau', 'power bi'],
  'qa': ['qa', 'quality assurance', 'test engineer', 'selenium', 'cypress', 'jest', 'junit', 'sdet', 'automation testing', 'manual testing'],
  'ui/ux': ['ui/ux', 'ui design', 'ux design', 'figma', 'wireframing', 'prototyping', 'user experience', 'user interface'],
  'cybersecurity': ['cybersecurity', 'cyber security', 'infosec', 'penetration testing', 'ethical hacking', 'soc analyst', 'vulnerability'],
  'salesforce': ['salesforce', 'sfdc', 'apex'],
  'sap': ['sap', 'sap abap', 'sap fico'],
  'agile': ['agile', 'scrum', 'kanban', 'jira'],
  'sales': ['sales', 'b2b sales', 'business development', 'lead generation', 'cold calling', 'account executive'],
  'marketing': ['marketing', 'digital marketing', 'seo', 'sem', 'content marketing', 'social media marketing', 'google ads', 'growth marketing'],
  'hr': ['hr', 'human resources', 'talent acquisition', 'recruitment', 'recruiting', 'onboarding', 'payroll'],
  'customer service': ['customer service', 'customer support', 'helpdesk', 'client support', 'zendesk'],
  'accounting': ['accounting', 'bookkeeping', 'quickbooks', 'accounts payable', 'accounts receivable', 'financial reporting'],
  'finance': ['financial analysis', 'corporate finance', 'financial modeling', 'budgeting', 'forecasting'],
  'legal': ['legal', 'contracts', 'compliance', 'regulatory compliance', 'paralegal'],
};

const SKILL_ALIASES = {
  java: 'java',
  python: 'python',
  js: 'javascript',
  javascript: 'javascript',
  ts: 'typescript',
  typescript: 'typescript',
  react: 'react',
  reactjs: 'react',
  node: 'node.js',
  nodejs: 'node.js',
  'node.js': 'node.js',
  express: 'express',
  golang: 'go',
  go: 'go',
  rust: 'rust',
  cpp: 'c++',
  'c++': 'c++',
  csharp: 'c#',
  'c#': 'c#',
  dotnet: 'c#',
  '.net': 'c#',
  php: 'php',
  ruby: 'ruby',
  rails: 'ruby',
  swift: 'swift',
  kotlin: 'kotlin',
  flutter: 'flutter',
  'react native': 'react native',
  sql: 'sql',
  mysql: 'sql',
  postgres: 'sql',
  postgresql: 'sql',
  mongodb: 'mongodb',
  mongo: 'mongodb',
  redis: 'redis',
  aws: 'aws',
  azure: 'azure',
  gcp: 'gcp',
  docker: 'docker',
  kubernetes: 'kubernetes',
  k8s: 'kubernetes',
  devops: 'devops',
  sre: 'devops',
  linux: 'linux',
  git: 'git',
  github: 'git',
  ml: 'machine learning',
  'machine learning': 'machine learning',
  ai: 'machine learning',
  nlp: 'machine learning',
  'data science': 'data science',
  qa: 'qa',
  testing: 'qa',
  sdet: 'qa',
  'ui/ux': 'ui/ux',
  figma: 'ui/ux',
  design: 'ui/ux',
  cybersecurity: 'cybersecurity',
  security: 'cybersecurity',
  sales: 'sales',
  marketing: 'marketing',
  seo: 'marketing',
  hr: 'hr',
  recruiting: 'hr',
  accounting: 'accounting',
  finance: 'finance',
  legal: 'legal',
};

module.exports = {
  TECHNICAL_KEYWORDS,
  NON_TECHNICAL_KEYWORDS,
  TECHNICAL_CATEGORIES,
  NON_TECHNICAL_CATEGORIES,
  ALL_SKILLS,
  SKILL_EXTRACT,
  SKILL_ALIASES,
};
